# Generated by Django 4.2.30 on 2026-09-10 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Aguardando confirmação'), ('CONFIRMED', 'Confirmado'), ('SHIPPED', 'Em trânsito'), ('DELIVERED', 'Entregue'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Status')),
                ('total', models.DecimalField(decimal_places=2, help_text='Valor total calculado no momento da finalização do pedido.', max_digits=10, verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10, verbose_name='Tamanho')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Preço no momento da compra (snapshot).', max_digits=10, verbose_name='Preço unitário')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Item do pedido',
                'verbose_name_plural': 'Itens do pedido',
            },
        ),
    ]
