# Generated by Django 4.2.30 on 2026-09-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_address_shipping_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Aguardando confirmação'), ('CONFIRMED', 'Confirmado'), ('SHIPPED', 'Em trânsito'), ('DELIVERED', 'Entregue'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Status do pedido'),
        ),
    ]
